# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QGroupBox,
    QLabel, QPushButton, QSizePolicy, QSlider,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1119, 923)
        Form.setStyleSheet(u"")
        self.graphicsView = QGraphicsView(Form)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(20, 310, 491, 471))
        self.graphicsView_2 = QGraphicsView(Form)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(560, 310, 521, 481))
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 20, 201, 51))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(u"background-color: rgb(43, 255, 160);")
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 100, 251, 201))
        self.groupBox.setStyleSheet(u"background-color: rgb(170, 170, 127);")
        self.pushButton_2 = QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 40, 201, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.pushButton_2.setFont(font1)
        self.pushButton_2.setStyleSheet(u"background-color: rgb(252, 252, 252);")
        self.pushButton_3 = QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(20, 80, 201, 31))
        self.pushButton_3.setFont(font1)
        self.pushButton_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 120, 201, 31))
        self.pushButton_4.setFont(font1)
        self.pushButton_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton_5 = QPushButton(self.groupBox)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(20, 160, 201, 31))
        self.pushButton_5.setFont(font1)
        self.pushButton_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 10, 171, 16))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        self.label_10.setFont(font2)
        self.pushButton_6 = QPushButton(Form)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(290, 190, 151, 61))
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(u"background-color: rgb(170, 170, 127);")
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(460, 20, 301, 271))
        self.groupBox_2.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.groupBox_2.setStyleSheet(u"background-color: rgb(170, 170, 127);")
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 201, 21))
        self.label.setFont(font2)
        self.gaussian_slider = QSlider(self.groupBox_2)
        self.gaussian_slider.setObjectName(u"gaussian_slider")
        self.gaussian_slider.setGeometry(QRect(150, 40, 121, 22))
        self.gaussian_slider.setMaximum(25)
        self.gaussian_slider.setSliderPosition(3)
        self.gaussian_slider.setOrientation(Qt.Horizontal)
        self.median_slider = QSlider(self.groupBox_2)
        self.median_slider.setObjectName(u"median_slider")
        self.median_slider.setGeometry(QRect(150, 100, 121, 22))
        self.median_slider.setMinimum(0)
        self.median_slider.setMaximum(25)
        self.median_slider.setValue(3)
        self.median_slider.setSliderPosition(3)
        self.median_slider.setOrientation(Qt.Horizontal)
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 160, 271, 31))
        self.label_2.setFont(font2)
        self.slider_x = QSlider(self.groupBox_2)
        self.slider_x.setObjectName(u"slider_x")
        self.slider_x.setGeometry(QRect(190, 200, 91, 22))
        self.slider_x.setOrientation(Qt.Horizontal)
        self.rotationSlider = QSlider(self.groupBox_2)
        self.rotationSlider.setObjectName(u"rotationSlider")
        self.rotationSlider.setGeometry(QRect(190, 240, 91, 22))
        self.rotationSlider.setOrientation(Qt.Horizontal)
        self.pushButton_gaussian = QPushButton(self.groupBox_2)
        self.pushButton_gaussian.setObjectName(u"pushButton_gaussian")
        self.pushButton_gaussian.setGeometry(QRect(10, 40, 93, 28))
        self.pushButton_gaussian.setStyleSheet(u"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.bilateral_slider = QSlider(self.groupBox_2)
        self.bilateral_slider.setObjectName(u"bilateral_slider")
        self.bilateral_slider.setGeometry(QRect(150, 130, 121, 22))
        self.bilateral_slider.setMaximum(25)
        self.bilateral_slider.setSliderPosition(3)
        self.bilateral_slider.setOrientation(Qt.Horizontal)
        self.pushButton_median = QPushButton(self.groupBox_2)
        self.pushButton_median.setObjectName(u"pushButton_median")
        self.pushButton_median.setGeometry(QRect(10, 100, 93, 28))
        self.pushButton_median.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton_bilateral = QPushButton(self.groupBox_2)
        self.pushButton_bilateral.setObjectName(u"pushButton_bilateral")
        self.pushButton_bilateral.setGeometry(QRect(10, 130, 93, 28))
        self.pushButton_bilateral.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 200, 91, 20))
        self.label_8.setStyleSheet(u"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(90, 240, 71, 21))
        self.label_9.setStyleSheet(u"font: 75 10pt \"MS Shell Dlg 2\";")
        self.slider_y = QSlider(self.groupBox_2)
        self.slider_y.setObjectName(u"slider_y")
        self.slider_y.setGeometry(QRect(30, 190, 22, 71))
        self.slider_y.setOrientation(Qt.Vertical)
        self.mean_slider = QSlider(self.groupBox_2)
        self.mean_slider.setObjectName(u"mean_slider")
        self.mean_slider.setGeometry(QRect(150, 70, 121, 21))
        self.mean_slider.setMaximum(25)
        self.mean_slider.setSliderPosition(3)
        self.mean_slider.setOrientation(Qt.Horizontal)
        self.pushButton_mean = QPushButton(self.groupBox_2)
        self.pushButton_mean.setObjectName(u"pushButton_mean")
        self.pushButton_mean.setGeometry(QRect(10, 70, 93, 28))
        self.pushButton_mean.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton_gaussian.raise_()
        self.label.raise_()
        self.gaussian_slider.raise_()
        self.median_slider.raise_()
        self.label_2.raise_()
        self.slider_x.raise_()
        self.rotationSlider.raise_()
        self.bilateral_slider.raise_()
        self.pushButton_median.raise_()
        self.pushButton_bilateral.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.slider_y.raise_()
        self.mean_slider.raise_()
        self.pushButton_mean.raise_()
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(770, 50, 341, 241))
        self.groupBox_3.setStyleSheet(u"background-color: rgb(170, 170, 127);")
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 0, 161, 31))
        self.label_3.setFont(font2)
        self.pushButton_9 = QPushButton(self.groupBox_3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(10, 90, 201, 31))
        self.pushButton_9.setFont(font1)
        self.pushButton_9.setStyleSheet(u"background-color: rgb(252, 252, 252);")
        self.pushButton_8 = QPushButton(self.groupBox_3)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(10, 140, 201, 31))
        self.pushButton_8.setFont(font1)
        self.pushButton_8.setStyleSheet(u"background-color: rgb(252, 252, 252);")
        self.pushButton_10 = QPushButton(self.groupBox_3)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(10, 190, 201, 31))
        self.pushButton_10.setFont(font1)
        self.pushButton_10.setStyleSheet(u"background-color: rgb(252, 252, 252);")
        self.pushButton_11 = QPushButton(self.groupBox_3)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(10, 40, 201, 31))
        self.pushButton_11.setFont(font1)
        self.pushButton_11.setStyleSheet(u"background-color: rgb(252, 252, 252);")
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(180, 0, 151, 31))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        font3.setKerning(True)
        self.label_6.setFont(font3)
        self.thresholdValue = QSlider(self.groupBox_3)
        self.thresholdValue.setObjectName(u"thresholdValue")
        self.thresholdValue.setGeometry(QRect(260, 40, 22, 160))
        self.thresholdValue.setOrientation(Qt.Vertical)
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(220, 200, 111, 31))
        font4 = QFont()
        font4.setPointSize(7)
        font4.setBold(True)
        self.label_7.setFont(font4)
        self.label_7.setFrameShape(QFrame.NoFrame)
        self.label_7.setFrameShadow(QFrame.Plain)
        self.label_7.setLineWidth(3)
        self.label_7.setMidLineWidth(0)
        self.pushButton_7 = QPushButton(Form)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(10, 860, 121, 51))
        font5 = QFont()
        font5.setPointSize(14)
        self.pushButton_7.setFont(font5)
        self.pushButton_7.setStyleSheet(u"background-color: rgb(255, 71, 71);")
        self.pushButton_12 = QPushButton(Form)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(150, 860, 131, 51))
        self.pushButton_12.setFont(font5)
        self.pushButton_12.setStyleSheet(u"background-color: rgb(24, 255, 59);")
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(200, 790, 121, 31))
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"background-color: rgb(170, 162, 157);")
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(800, 810, 101, 31))
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"background-color: rgb(170, 162, 157);")

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Load Image", None))
        self.groupBox.setTitle("")
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Perwit", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"Robert", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"Canny", None))
        self.pushButton_5.setText(QCoreApplication.translate("Form", u"LOG", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Edge Detection", None))
        self.pushButton_6.setText(QCoreApplication.translate("Form", u"Morophology", None))
        self.groupBox_2.setTitle("")
        self.label.setText(QCoreApplication.translate("Form", u"Smoothing-Filter", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Translation & Rotation", None))
        self.pushButton_gaussian.setText(QCoreApplication.translate("Form", u"Gaussian", None))
        self.pushButton_median.setText(QCoreApplication.translate("Form", u"Median", None))
        self.pushButton_bilateral.setText(QCoreApplication.translate("Form", u"Bilateral", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Translation", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Rotation", None))
        self.pushButton_mean.setText(QCoreApplication.translate("Form", u"Mean", None))
        self.groupBox_3.setTitle("")
        self.label_3.setText(QCoreApplication.translate("Form", u"Segmentaion", None))
        self.pushButton_9.setText(QCoreApplication.translate("Form", u"Manual Seg", None))
        self.pushButton_8.setText(QCoreApplication.translate("Form", u"Adaptive Histogram", None))
        self.pushButton_10.setText(QCoreApplication.translate("Form", u"Otsu", None))
        self.pushButton_11.setText(QCoreApplication.translate("Form", u"Histogram Peak Seg", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Threshold Slider", None))
        self.label_7.setText("")
        self.pushButton_7.setText(QCoreApplication.translate("Form", u"Reset", None))
        self.pushButton_12.setText(QCoreApplication.translate("Form", u"Save", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"The Original", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"The Result", None))
    # retranslateUi

